#!/usr/bin/env bash
# Script to install Nginx Server
apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
service nginx start
