#!/usr/bin/env bash
# Script to install, configure Nginx web Server
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
sudo rm /var/www/html/index.nginx-debian.html
touch /var/www/html/index.hmtl
sudo echo 'Hello World!' > /var/www/html/index.html
if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
