#!/usr/bin/env bash
# Create redirect
INDEX_COPY="Hello World!"

sudo apt update -y
sudo apt install nginx -y
sudo rm /var/www/html/index.nginx-debian.html
echo "$INDEX_COPY" | sudo tee /var/www/html/index.html > /dev/null
newlines="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "26i $newlines" /etc/nginx/sites-available/default
sudo service nginx start
