#!/usr/bin/env bash
# Fixes the nginx listening port and reloads the nginx master process
sudo apt-get nginx -y
sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
